### PR TITLE
Add a new test-e2e-local target 

### PR DESCRIPTION
**Pull request by exdx**
Adds a new makefile target that that builds binaries locally, deploys rukpak, and then runs the e2e suite. This target is helpful for local testing, because the existing e2e target builds the binaries in a container and takes several minutes to just get started.

### CODE REVIEW

**Comment by joelanford** [comment]
I ran into this too. My initial thought was "rather than adding yet another make target that does something different than what CI does, can we use `Dockerfile.local` as _the_ Dockerfile for `make run` and `make e2e`.

Basically `git mv Dockerfile.local Dockerfile`, consolidate `build-local-container` and `build-container` make targets, and then fix whatever else up. 

I started looking into that and I think I ran into an issue with how that would work in a platform agnostic way.  It should be doable, though I think. I just didn't have the time to chase it.

**Comment by joelanford** [comment]
Another potential option to consolidate even further is to use `GOOS=linux goreleaser build --single-target` to build the binaries and then see if `build-container` could make use of the goreleaser Dockerfile.

**Comment by joelanford** [comment]
Alright check out #186 as an alternative.

That PR highlights to me that we need to:
- consolidate the `deploy` and `goreleaser` workflows (covered by #187)
- add build targets to `goreleaser` for multi-arch support (covered by #53)

**Comment by exdx** [comment]
I think consolidating down to one Dockerfile per #186 is the better approach. Closing this one out in favor of that PR.

**Pull request closed without merging**
