### PR TITLE
Makefile,cmd: Move the core main.go to it's own cmd directory

### PR DESCRIPTION
**Pull request by timflannagan**
Move the cmd/main.go executable package, which is responsible for standing up the Bundle webhook to it's own nested cmd directory.

Before tree structure:

```console
$ tree cmd
cmd
├── main.go
└── unpack
    └── main.go

```

After tree structure:

```console
$ tree cmd
cmd
├── core
│   └── main.go
└── unpack
    └── main.go
```

Signed-off-by: timflannagan <timflannagan@gmail.com>

### CODE REVIEW

**Comment by timflannagan** [comment]
Note: we don't have to push this through if we prefer the current setup but I noticed this locally and making these changes took two minutes.

**Comment by joelanford** [comment]
+1 from me. I also noticed and just hadn't gotten around to submitting this.

**Comment by timflannagan** [comment]
> +1 from me. I also noticed and just hadn't gotten around to submitting this.

Sounds good - it looks like I also needed to push up a .goreleaser fix to make CI happy but we can let others whey in too if necessary.

**Review by akihikokuroda — APPROVED** [review]
Thanks for fixing this!

**Pull request merged**
