### PR TITLE
Addresses Open Issues with Commit #375

### PR DESCRIPTION
**Pull request by nsapse**
Attempts to fix open comments left on [PR#375](https://github.com/operator-framework/rukpak/pull/375) after merge.

### CODE REVIEW

**Review by timflannagan — COMMENTED** [review]
Thanks for the quick follow up - a couple of things:

- Can we drop the unrelated commit that introduces a new GHA workflow?
- Can we update the commit to describe adding kind to the hack/tools module?
- Can we update the e2e workflow and use `kind` Makefile target instead of download the kind binary manually?

**Comment by timflannagan** [comment]
@nsapse Can you add the "Closes #365" to your PR description?

**Comment by nsapse** [comment]
I've re-run the tests twice now and it keeps failing `the bundle name is too long` which seems oddly specific and it's not immediately clear to me why changing the kind binary would modify that.

**Comment by nsapse** [comment]
Looking further the test shows that the code is failing as expected but with a slightly different error message than predicted. Is it possible someone modified the error being returned without updating the tests?

**Comment by nsapse** [comment]
Failed test was fixed by rolling back kind from 0.13.0 -> 0.12.0. Had inadvertently upgraded as part of original pr.

**Review by timflannagan — APPROVED** [review]

**Review by exdx — APPROVED** [review]

**Pull request merged**
