### PR TITLE
Add uninstall target

### PR DESCRIPTION
**Pull request by exdx**
Adds an uninstall target to conveniently remove rukpak from the cluster
entirely. Relies on the kustomize output to build a list of objects to
remove.

<details>

```
rukpak(main): kustomize build manifests | kubectl delete -f -
namespace "crdvalidator-system" deleted
namespace "rukpak-system" deleted
customresourcedefinition.apiextensions.k8s.io "bundleinstances.core.rukpak.io" deleted
customresourcedefinition.apiextensions.k8s.io "bundles.core.rukpak.io" deleted
serviceaccount "crd-validation-webhook" deleted
serviceaccount "plain-provisioner-admin" deleted
serviceaccount "rukpak-core-admin" deleted
clusterrole.rbac.authorization.k8s.io "bundle-reader" deleted
clusterrole.rbac.authorization.k8s.io "crd-validation-webhook" deleted
clusterrole.rbac.authorization.k8s.io "plain-provisioner-admin" deleted
clusterrolebinding.rbac.authorization.k8s.io "crd-validation-webhook" deleted
clusterrolebinding.rbac.authorization.k8s.io "plain-provisioner-admin" deleted
service "crd-validation-webhook" deleted
service "plain-provisioner" deleted
service "rukpak-webhook-service" deleted
deployment.apps "crd-validation-webhook" deleted
deployment.apps "plain-provisioner" deleted
deployment.apps "rukpak-core-webhook" deleted
certificate.cert-manager.io "crd-validation-webhook-certificate" deleted
certificate.cert-manager.io "rukpak-webhook-certificate" deleted
issuer.cert-manager.io "selfsigned" deleted
issuer.cert-manager.io "rukpak-selfsigned" deleted
validatingwebhookconfiguration.admissionregistration.k8s.io "crd-validation-webhook" deleted
validatingwebhookconfiguration.admissionregistration.k8s.io "rukpak-validating-webhook-configuration" deleted
```
</details>

### CODE REVIEW

**Review by joelanford — APPROVED** [review]

**Review by timflannagan — APPROVED** [review]
Alternatively: `kubectl delete -k manifests`?

**Comment by joelanford** [comment]
> kubectl delete -k manifests

If that works for apply and delete, we could drop our kustomize dep entirely right?

**Comment by timflannagan** [comment]
@joelanford Not necessarily as we're reliant on `kustomize build` to render the installation release manifests: https://github.com/operator-framework/rukpak/blob/main/Makefile#L189.

**Comment by exdx** [comment]
> Alternatively: `kubectl delete -k manifests`?

That looks good, but I got the following trying it locally:
```
$: kubectl delete -k manifests
error: AccumulateTarget: couldn't make target for ./crds: json: cannot unmarshal object into Go struct field Kustomization.patchesStrategicMerge of type patch.StrategicMerge
```

not sure if you're seeing this locally as well, or maybe there is more to it.

**Comment by timflannagan** [comment]
@exdx Weird - this worked for me locally:

```console
$ k delete -k manifests
k delete -k manifests
namespace "crdvalidator-system" deleted
namespace "rukpak-system" deleted
customresourcedefinition.apiextensions.k8s.io "bundleinstances.core.rukpak.io" deleted
customresourcedefinition.apiextensions.k8s.io "bundles.core.rukpak.io" deleted
serviceaccount "crd-validation-webhook" deleted
serviceaccount "plain-provisioner-admin" deleted
serviceaccount "rukpak-core-admin" deleted
clusterrole.rbac.authorization.k8s.io "bundle-reader" deleted
clusterrole.rbac.authorization.k8s.io "crd-validation-webhook" deleted
clusterrole.rbac.authorization.k8s.io "plain-provisioner-admin" deleted
clusterrolebinding.rbac.authorization.k8s.io "crd-validation-webhook" deleted
...
```

I'm using a 1.21 k8s client version btw.

**Comment by timflannagan** [comment]
> @joelanford Not necessarily as we're reliant on kustomize build to render the installation release manifests: https://github.com/operator-framework/rukpak/blob/main/Makefile#L189.

I realize there's a kubectl kustomize sub-command that can tackle this mirror this process. Maybe we need to replace the hack/tools entry for kustomize with kubectl, or is that overkill?

**Comment by joelanford** [comment]
There's also this way to do it: `kubectl create -k manifests --dry-run=client -o yaml`

> Maybe we need to replace the hack/tools entry for kustomize with kubectl, or is that overkill?

Not necessarily, though I'd probably try to align the kubectl version we depend on the our main `k8s.io/client-go` version in go.mod.

**Review by tylerslaton — APPROVED** [review]

**Comment by exdx** [comment]
Ok, nice `kubectl delete -k manifests` worked for me after updating my kubectl client. Updated PR to use this command instead.

**Pull request merged**
