### PR TITLE
move some internal code to pkg

### PR DESCRIPTION
**Pull request by akihikokuroda**
as a part of phase 1 of #425, this PR moves 

`source`, `storage`, `updater` `version` `finalizer` and some methods in `util` to `pkg`

### CODE REVIEW

**Comment by joelanford** [comment]
@akihikokuroda did you link the right parent issue? #452 seems to be unrelated.

**Comment by akihikokuroda** [comment]
@joelanford Sorry. it is #425

**Comment by joelanford** [comment]
Ah! Thanks. Do we have an out-of-tree provisioner we're working on? That might help drive prioritize where to improve our various "provisioner-runtime" sorts of packages and also drive what is made public at all.

Not sure what others think, but my preference would be to have a specific motivation for each thing we make public. Reason being that once we call rukpak 1.0, we'd be making the commitment that those public packages would not have any breaking changes.

At that point, we could always decide to move those library bits to a separate repo to separate the versions of the APIs/controllers from the underlying libraries.

**Comment by akihikokuroda** [comment]
I see.  I saw #460 referencing #425.  If it doesn't get priority, this work should wait then.

**Comment by timflannagan** [comment]
Yep, my preference would be to keep everything internal. I think we've discussed this before, and someone (Joe?) made the argument that we're an alpha level project, and therefore external repositories importing packages defined in this repository under pkg/ don't have the same API surface guarantees we live to make in other OLM projects.

**Comment by timflannagan** [comment]
With that said, we may want to start thinking about what needs to live in core rukpak over the next couple of releases if the maintenance burden of additional provisioner requirements is too substantial for it to live in-tree.

**Comment by akihikokuroda** [comment]
I close this PR.

**Pull request closed without merging**
